apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: lets-encrypt-prod-issuer
  namespace: sonarqube
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "rafael@nibo.com.br"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: sonarqube
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sonarqube-tls
  namespace: sonarqube
spec:
  secretName: sonarqube-tls
  issuerRef:
    name: lets-encrypt-prod-issuer
    kind: Issuer
  commonName: sonarqube.nibo.com.br
  dnsNames:
    - sonarqube.nibo.com.br